name: icapps_generator
description: Dart tool to automaticly generate new code when creating a new screen.
version: 0.3.0
author: Koen Van Looveren <koen.vanlooveren@icapps.com>
homepage: https://github.com/icapps/flutter-icapps-generator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path: ^1.6.4
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.9.4
